repositoryUrl: https://github.com/dynamsoft-docs/web-twain-docs/blob/master
firstLevelUrl: /web-twain/docs
repository: dynamsoft-docs/web-twain-docs
docFullPath: https://www.dynamsoft.com/web-twain/docs
productUrl: https://www.dynamsoft.com/web-twain/overview/
productName: Dynamic Web TWAIN
docHomePage: /web-twain/docs/
dynamsoft_logo: /web-twain/docs/assets/img-icon/dynamsoft-logo.png
dwt_logo: /web-twain/docs/assets/img-icon/dwt-logo.png
edit_icon: /web-twain/docs/assets/img-icon/edit-icon.png

assets: /web-twain/docs/assets/
_includes: /web-twain/docs/_includes/
_layouts: /web-twain/docs/_layouts/
about: /web-twain/docs/about/
getstarted: /web-twain/docs/getstarted/
indepth: /web-twain/docs/indepth/
info: /web-twain/docs/info/
faq: /web-twain/docs/faq/

dynamsoft_logo: /web-twain/docs/assets/img-icon/dynamsoft-logo.png
dbr_logo: /web-twain/docs/assets/img-icon/dbr-logo.png
edit_icon: /web-twain/docs/assets/img-icon/edit-icon.png
smile_icon: /web-twain/docs/assets/img-icon/icon-smile.png
sad_icon: /web-twain/docs/assets/img-icon/icon-sad.png
dbr_icon: /web-twain/docs/assets/img-icon/icon-dbr.svg
dwt_icon: /web-twain/docs/assets/img-icon/icon-dwt.svg
dnt_icon: /web-twain/docs/assets/img-icon/icon-dnt.svg

baseurl: /web-twain/docs/

useVersionTreeV2: true

webp:
  enabled: true
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75
  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets/img-icon", "/assets/imgs/"]
  # Whether to search in nested directories or not
  nested: true
  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]
  # File extensions for animated gif files 
  gifs: [".gif"]
  # Set to true to always regenerate existing webp files
  regenerate: false
  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  # Eg : "/usr/local/bin/cwebp"
  webp_path: nil
  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []
  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false

plugins:
  - jemoji
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag

url: "https://www.dynamsoft.com" # sitemap root
